# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]


env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package
      run: |
        mkdir dist/
        mkdir dist/lib

        mv 实时打字翻译 -网页版(推荐).exe dist/
        mv lib/32bit dist/lib/
        mv lib/64bit dist/lib/
        mv lib/dll_64 dist/lib/
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Real-time-translation-typing
        path: dist/
